FROM debian:latest

ENV NAME=debian-toolbox VERSION=latest
LABEL com.github.containers.toolbox="true" \
  name="$NAME" \
  version="$VERSION" \
  usage="This image is meant to be used with the toolbox command" \
  summary="Base image for creating Debian toolbox containers"

ADD fs /
RUN bash /build/install.sh

ENTRYPOINT []
